spring.application.name=ai-copilot-service
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:h2:mem:aicopilotservice
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

jwt.secret=ThisIsASecretKeyForHealthcareJwtSecurityThisIsASecretKeyForHealthcareJwtSecurity
jwt.expiration=86400000
