package com.healthconnector.app.constants;

/**
 * All auditable actions tracked in the audit log.
 */
public enum AuditAction {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    USER_CREATED,
    USER_UPDATED,
    USER_BLOCKED,
    USER_ACTIVATED,
    USER_DELETED,
    AUTHORIZATION_CREATED,
    AUTHORIZATION_UPDATED,
    AUTHORIZATION_SUBMITTED,
    AUTHORIZATION_APPROVED,
    AUTHORIZATION_REJECTED,
    AUTHORIZATION_MORE_INFO_REQUESTED,
    AUTHORIZATION_COMPLETED,
    AUTHORIZATION_DELETED,
    AI_REVIEW_TRIGGERED,
    AI_REVIEW_COMPLETED,
    MESSAGE_SENT,
    NOTIFICATION_SENT,
    SYSTEM_CONFIG_UPDATED,
    FHIR_VALIDATION_TRIGGERED,
    REFRESH_TOKEN_ISSUED
}
