# Application
spring.application.name=healthcare-connector

# Server
server.port=8080

# H2 Database Configuration (File-based - persistent)
spring.datasource.url=jdbc:h2:file:./data/healthdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin


# Spring JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Disable SQL initialization (prevents data.sql/schema.sql auto-loading)
#spring.sql.init.mode=never
