spring.application.name=healthcare-connector
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=rootroot

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
gemini.api.key=YOUR_GEMINI_API_KEY_HERE
gemini.model=gemini-2.5-flash