spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=ThisIsASecretKeyForHealthcareJwtSecurityThisIsASecretKeyForHealthcareJwtSecurity
jwt.expiration=86400000

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=provider-service
spring.cloud.gateway.routes[1].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/provider/**

spring.cloud.gateway.routes[2].id=payer-service
spring.cloud.gateway.routes[2].uri=lb://PAYER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/payer/**

spring.cloud.gateway.routes[3].id=authorization-service
spring.cloud.gateway.routes[3].uri=lb://AUTHORIZATION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/authorization/**

spring.cloud.gateway.routes[4].id=ai-copilot-service
spring.cloud.gateway.routes[4].uri=lb://AI-COPILOT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/ai/**

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/notification/**


############################################
# CORS Configuration
############################################

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
